version: 0.0
os: linux
files:
  - source: codedeploy/ec2/scripts/
    destination: /application/scripts
permissions:
  - object: /application/scripts
    pattern: "*.sh"
    mode: 744
# The location of scripts you specify in the hooks section is relative to the root of the application revision bundle
hooks: 
  ApplicationStart:
    - location: codedeploy/ec2/scripts/start-app.sh
      timeout: 180
  ValidateService:
    - location: codedeploy/ec2/scripts/validate-svc.sh
      timeout: 180
  # ApplicationStop is called when deploy the next version
  ApplicationStop:
    - location: codedeploy/ec2/scripts/stop-app.sh
      timeout: 180