version: 0.0
os: linux
files:
  - source: codedeploy/ec2/scripts/
    destination: /application/scripts
hooks:
  ApplicationStop:
    - location: scripts/stop-app.sh
  ApplicationStart:
    - location: scripts/start-app.sh
  ValidateService:
    - location: scripts/validate-svc.sh