version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-21-openjdk"

phases:
  build:
    commands:
      - mvn package

artifacts:
  files:
    - 'target/simple-springboot-0.0.1-SNAPSHOT.jar'
    
cache:
  paths:
    - '/root/.m2/**/*'
